### ISSUE TITLE
[0.4.3.3] 词条更改后漏抓

### ISSUE THREAD

**Issue by Khaos423** [NumberSir/DoL-I18n-Build#4]
### 文件位置

base-combat/tentacles/tentacleActionsGeneration.twee

### 漏抓原文

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Glang/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Glang/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

漏抓 | 多键
-- | --
<<set   _leftaction["("+$angelBanish+" /   "+$angelBanishMax+") Banish the"] to   "leftbanish">> | 各两处
<<set   _rightaction["("+$angelBanish+" /   "+$angelBanishMax+") Banish the"] to   "rightbanish">>

</body>

</html>

### 备注

原词条是`["($angelBanish / $angelBanishMax) Banish the"]`，
更改为`["("+$angelBanish+" / "+$angelBanishMax+") Banish the"]`后的词条漏抓。

### 问题来源

对比commit翻译时发现。

不紧急的补充问题

1. 给 link 加图片或者改图片更新后会出现很多未翻译词条，可能以后会少了，不过如果能检测 link 前新增和更改的<<图片调用>>然后批量复制译文能减少工作量。

2. 词条中有一些是和失效词条完全一样的，这次更新后也有些改动过的词条同时保留原词条和新增失效词条，可能需要处理一下。

临近期末大家都没什么时间，这两个问题可以不着急，辛苦羊神了。

**Comment by NumberSir** [comment]
等 0.5.x.x 统一把正常词条里的失效词条去掉好了，现在不去掉主要是因为没办法保留在编辑痕迹的同时自动挪进失效词条分类里，如果强制删除的话有些人的贡献就掉了，手动挪的话又不可能，先研究研究怎么写个脚本挪
