### ISSUE TITLE
两个漏抓回报

### ISSUE THREAD

**Issue by SenriYuki** [NumberSir/DoL-I18n-Build#5]
### 文件位置

overworld-town/loc-school/widgets-events.csv

### 漏抓原文

看到那个东西你起了一身的鸡皮疙瘩，一个<<eventwhitneyparasiteadjective>>的想法浮现在你的脑海里。<<Hes>>不会做出你想的那种事的，对吧？

艾力克斯那个我实在搜不到文本可能我用的方式不太正确。

![IMG20231230053537](https://github.com/NumberSir/DoL-I18n-Build/assets/153801145/5447aad3-2264-4fe2-b2ac-8edc75764ded)
![IMG20231230053554](https://github.com/NumberSir/DoL-I18n-Build/assets/153801145/ef5317a0-b34a-423e-8a91-8ea2c80732ff)

**Comment by SenriYuki** [comment]
再加一个

special-dance/actions.csv


![Screenshot_2023-12-30-08-56-58-02_c3a7877071fa066085f34e47f499198f](https://github.com/NumberSir/DoL-I18n-Build/assets/153801145/f7a6dab7-219e-4653-906e-f2c59e3618f9)

**Comment by omvjro** [comment]
这些应该不是漏抓，我在 ParaTranz 上改了。
