### ISSUE TITLE
医疗特质漏抓

### ISSUE THREAD

**Issue by omvjro** [NumberSir/DoL-I18n-Build#7]
### 文件位置

base-system/overlays/traits.twee

### 漏抓原文

``return ` `` 开头的2条
`let result = ` 开头的5条
含 `result += ` 的17条

### 问题来源

![9a3ae7af4aabc426921d76681149c823](https://github.com/NumberSir/DoL-I18n-Build/assets/144692181/dea4d66b-4c59-4ca2-ae7f-5767c68a482c)

**Comment by NumberSir** [comment]
https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/254
