### ISSUE TITLE
史莱姆强行点菜 switch 需要抓取

### ISSUE THREAD

**Issue by omvjro** [NumberSir/DoL-I18n-Build#9]
### 文件位置

overworld-town/loc-cafe/widgets.twee

### 漏抓原文

`<<case "` 开头 8 处

### 备注

参与 switch 的 `$daily.earSlimeOceanBreezeCafeEat` 也参与显示，抓取可以避免 replace。

**Comment by NumberSir** [comment]
https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/266

**Comment by NumberSir** [comment]
`$daily.earSlimeOceanBreezeCafeEat` 是 `_cafeOptions`，已经汉化完了
